CLUSTER:
  ON_CLUSTER: False
DATA_LOADER:
 NUM_THREADS: 8
DEDUP_BOXES: 0.0625
EPS: 1e-14
EXPECTED_RESULTS: []
EXPECTED_RESULTS_ATOL: 0.005
EXPECTED_RESULTS_EMAIL: ''
EXPECTED_RESULTS_RTOL: 0.1
FAST_RCNN:
  CONV_HEAD_DIM: 256
  MLP_HEAD_DIM: 2048
  NUM_STACKED_CONVS: 4
  ROI_BOX_HEAD: 'fast_rcnn_heads.add_roi_2mlp_head'
  ROI_XFORM_METHOD: 'RoIAlign'
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
FPN:
  COARSEST_STRIDE: 32
  DIM: 512
  EXTRA_CONV_LEVELS: False
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
  ROI_CANONICAL_LEVEL: 4
  ROI_CANONICAL_SCALE: 224
  ROI_MAX_LEVEL: 5
  ROI_MIN_LEVEL: 2
  RPN_ANCHOR_START_SIZE: 32
  RPN_ASPECT_RATIOS: (0.5, 1, 2)
  RPN_MAX_LEVEL: 6
  RPN_MIN_LEVEL: 2
  USE_GN: False
  ZERO_INIT_LATERAL: False
GROUP_NORM:
 DIM_PER_GP: -1
 EPSILON: 1e-05
 NUM_GROUPS: 32
KRCNN:
  CONV_HEAD_DIM: 256
  CONV_HEAD_KERNEL: 3
  CONV_INIT: 'GaussianFill'
  DECONV_DIM: 256
  DECONV_KERNEL: 4
  DILATION: 1
  HEATMAP_SIZE: -1
  INFERENCE_MIN_SIZE: 0
  KEYPOINT_CONFIDENCE: 'bbox'
  LOSS_WEIGHT: 1.0
  MIN_KEYPOINT_COUNT_FOR_VALID_MINIBATCH: 20
  NMS_OKS: False
  NORMALIZE_BY_VISIBLE_KEYPOINTS: True
  NUM_KEYPOINTS: -1
  NUM_STACKED_CONVS: 8
  ROI_KEYPOINTS_HEAD: ''
  ROI_XFORM_METHOD: 'RoIAlign'
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 0
  UP_SCALE: -1
  USE_DECONV: False
  USE_DECONV_OUTPUT: False
MATLAB: 'matlab'
MEMONGER: True
MEMONGER_SHARE_ACTIVATIONS: False
MODEL:
  BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0)
  CLS_AGNOSTIC_BBOX_REG: False
  CONV_BODY: 'FPN.add_fpn_ResNet101_conv5_body'
  EXECUTION_TYPE: 'dag'
  FASTER_RCNN: True
  KEYPOINTS_ON: False
  MASK_ON: False
  NUM_CLASSES: 353
  RPN_ONLY: False
  TYPE: 'generalized_rcnn'
MRCNN:
  CLS_SPECIFIC_MASK: True
  CONV_INIT: 'GaussianFill'
  DILATION: 2
  DIM_REDUCED: 256
  RESOLUTION: 14
  ROI_MASK_HEAD: ''
  ROI_XFORM_METHOD: 'RoIAlign'
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 0
  THRESH_BINARIZE: 0.5
  UPSAMPLE_RATIO: 1
  USE_FC_OUTPUT: False
  WEIGHT_LOSS_MASK: 1.0
NUM_GPUS: 8
OUTPUT_DIR: 'outputs'
PIXEL_MEANS: [[[ 102.9801,  115.9465,  122.7717]]]
RESNETS:
  NUM_GROUPS: 64
  RES5_DILATION: 1
  SHORTCUT_FUNC: 'basic_bn_shortcut'
  STEM_FUNC: 'basic_bn_stem'
  STRIDE_1X1: False
  TRANS_FUNC: 'bottleneck_transformation'
  WIDTH_PER_GROUP: 4
RETINANET:
  ANCHOR_SCALE: 4
  ASPECT_RATIOS: (0.5, 1.0, 2.0)
  BBOX_REG_BETA: 0.11
  BBOX_REG_WEIGHT: 1.0
  CLASS_SPECIFIC_BBOX: False
  INFERENCE_TH: 0.05
  LOSS_ALPHA: 0.25
  LOSS_GAMMA: 2.0
  NEGATIVE_OVERLAP: 0.4
  NUM_CONVS: 4
  POSITIVE_OVERLAP: 0.5
  PRE_NMS_TOP_N: 1000
  PRIOR_PROB: 0.01
  RETINANET_ON: False
  SCALES_PER_OCTAVE: 3
  SHARE_CLS_BBOX_TOWER: False
  SOFTMAX: False
RFCN:
 PS_GRID_SIZE: 3
RNG_SEED: 3
RPN:
  ASPECT_RATIOS: (0.5, 1, 2)
  RPN_ON: True
  SIZES: (64, 128, 256, 512)
  STRIDE: 16
SOLVER:
  BASE_LR: 0.005
  GAMMA: 0.1
  LOG_LR_CHANGE_THRESHOLD: 1.1
  LRS: []
  LR_POLICY: 'steps_with_decay'
  MAX_ITER: 90000
  MOMENTUM: 0.9
  SCALE_MOMENTUM: True
  SCALE_MOMENTUM_THRESHOLD: 1.1
  STEPS: [0, 60000, 80000]
  STEP_SIZE: 30000
  WARM_UP_FACTOR: 0.3333333333333333
  WARM_UP_ITERS: 500
  WARM_UP_METHOD: u'linear'
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_GN: 0.0
TEST:
  BBOX_AUG:
   AREA_TH_HI: 32400
   AREA_TH_LO: 2500
   ASPECT_RATIOS: ()
   ASPECT_RATIO_H_FLIP: False
   COORD_HEUR: 'UNION'
   ENABLED: False
   H_FLIP: False
   MAX_SIZE: 4000
   SCALES: ()
   SCALE_H_FLIP: False
   SCALE_SIZE_DEP: False
   SCORE_HEUR: 'UNION'
  BBOX_REG: True
  BBOX_VOTE:
   ENABLED: False
   SCORING_METHOD: 'ID'
   SCORING_METHOD_BETA: 1.0
   VOTE_TH: 0.8
  COMPETITION_MODE: True
  DATASETS: ('epic_val',)
  DETECTIONS_PER_IM: 100
  FORCE_JSON_DATASET_EVAL: True
  KPS_AUG:
   AREA_TH: 32400
   ASPECT_RATIOS: ()
   ASPECT_RATIO_H_FLIP: False
   ENABLED: False
   HEUR: 'HM_AVG'
   H_FLIP: False
   MAX_SIZE: 4000
   SCALES: ()
   SCALE_H_FLIP: False
   SCALE_SIZE_DEP: False
  MASK_AUG:
   AREA_TH: 32400
   ASPECT_RATIOS: ()
   ASPECT_RATIO_H_FLIP: False
   ENABLED: False
   HEUR: 'SOFT_AVG'
   H_FLIP: False
   MAX_SIZE: 4000
   SCALES: ()
   SCALE_H_FLIP: False
   SCALE_SIZE_DEP: False
  MAX_SIZE: 1333
  NMS: 0.5
  PRECOMPUTED_PROPOSALS: False
  PROPOSAL_FILES: ()
  PROPOSAL_LIMIT: 2000
  RPN_MIN_SIZE: 0
  RPN_NMS_THRESH: 0.7
  RPN_POST_NMS_TOP_N: 1000
  RPN_PRE_NMS_TOP_N: 1000
  SCALE: 800
  SCORE_THRESH: 0.05
  SOFT_NMS:
   ENABLED: False
   METHOD: 'linear'
   SIGMA: 0.5
  WEIGHTS: ''
TRAIN:
  ASPECT_GROUPING: True
  AUTO_RESUME: True
  BATCH_SIZE_PER_IM: 512
  BBOX_THRESH: 0.5
  BG_THRESH_HI: 0.5
  BG_THRESH_LO: 0.0
  CROWD_FILTER_THRESH: 0.7
  DATASETS: ('epic_train',)
  FG_FRACTION: 0.25
  FG_THRESH: 0.5
  FREEZE_CONV_BODY: False
  GT_MIN_AREA: 1
  IMS_PER_BATCH: 1
  MAX_SIZE: 1333
  PROPOSAL_FILES: ()
  RPN_BATCH_SIZE_PER_IM: 256
  RPN_FG_FRACTION: 0.5
  RPN_MIN_SIZE: 0
  RPN_NEGATIVE_OVERLAP: 0.3
  RPN_NMS_THRESH: 0.7
  RPN_POSITIVE_OVERLAP: 0.7
  RPN_POST_NMS_TOP_N: 2000
  RPN_PRE_NMS_TOP_N: 2000
  RPN_STRADDLE_THRESH: 0
  SCALES: (512, 544, 576, 608, 640, 672, 704, 736, 768, 800,)
  SNAPSHOT_ITERS: 20000
  USE_FLIPPED: True
  WEIGHTS: 'pretrained_weights/vg_1600_pre-trained_weights.pkl'
USE_NCCL: True
VIS: False
VIS_TH: 0.9
